apiVersion: v1
kind: Service
metadata:
  name: photo-service
  labels:
    app: photo-service
spec:
  type: "ClusterIP"
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3004
  selector:
    app: photo-service