apiVersion: v1
kind: Service
metadata:
  name: mobile-bff
  labels:
    app: mobile-bff
spec:
  type: "ClusterIP"
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: mobile-bff