apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: comment-service
  name: comment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: comment-service
  template:
    metadata:
      labels:
        app: comment-service
    spec:
      containers:
        - image: heyboonsong/learning:comment-service
          name: learning-comment-service
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
              ephemeral-storage: "100Mi"
            limits:
              cpu: "500m"
              memory: "500Mi" 
              ephemeral-storage: "200Mi"
          ports:
            - name: http
              containerPort: 3002
      restartPolicy: Always